export const eventCardsData = [
	{
		id: '1',
		isOnline: true,
		title: 'React Native Workshop',
		isFree: true,
		newPrice: 0,
		oldPrice: 0,
		participants: 120,
		date: 'June 15, 2025',
		image: '../../assets/images/dark/gmail-icon-dark.png',
	},
	{
		id: '2',
		isOnline: false,
		title: 'Advanced JS Conference',
		isFree: false,
		newPrice: 99,
		oldPrice: 199,
		participants: 300,
		date: 'July 5, 2025',
		image: '../../assets/images/dark/gmail-icon-dark.png',
	},
	{
		id: '3',
		isOnline: false,
		title: 'Advanced JS Conference',
		isFree: false,
		newPrice: 99,
		oldPrice: 199,
		participants: 300,
		date: 'July 5, 2025',
		image: '../../assets/images/dark/gmail-icon-dark.png',
	},
	{
		id: '4',
		isOnline: false,
		title: 'Advanced JS Conference',
		isFree: false,
		newPrice: 99,
		oldPrice: 199,
		participants: 300,
		date: 'July 5, 2025',
		image: '../../assets/images/dark/gmail-icon-dark.png',
	},
	{
		id: '5',
		isOnline: true,
		title: 'Advanced JS Conference',
		isFree: false,
		newPrice: 99,
		oldPrice: 199,
		participants: 300,
		date: 'July 5, 2025',
		image: '../../assets/images/dark/gmail-icon-dark.png',
	},
	{
		id: '6',
		isOnline: true,
		title: 'Advanced JS Conference',
		isFree: false,
		newPrice: 99,
		oldPrice: 199,
		participants: 300,
		date: 'July 5, 2025',
		image: '../../assets/images/dark/gmail-icon-dark.png',
	},
]
